import React from 'react';
import { Shield, FileCheck, Download, ArrowLeft } from 'lucide-react';
import { motion } from 'framer-motion';

const Ring = ({ score = 92 }) => {
  const radius = 56;
  const circumference = 2 * Math.PI * radius;
  const clamped = Math.max(0, Math.min(100, score));
  const offset = circumference - (clamped / 100) * circumference;

  return (
    <svg width="140" height="140" viewBox="0 0 140 140">
      <circle cx="70" cy="70" r={radius} stroke="rgba(255,255,255,0.15)" strokeWidth="10" fill="none" />
      <circle
        cx="70"
        cy="70"
        r={radius}
        stroke="#00FFE0"
        strokeWidth="10"
        fill="none"
        strokeDasharray={circumference}
        strokeDashoffset={offset}
        strokeLinecap="round"
      />
      <text x="70" y="76" textAnchor="middle" className="fill-white" fontSize="24" fontWeight="700">
        {clamped}%
      </text>
    </svg>
  );
};

const VerificationReport = ({ onBack, onRestart, fileName = 'Document', score = 92 }) => {
  const factors = [
    { name: 'Provenance', value: 0.95 },
    { name: 'Metadata Integrity', value: 0.9 },
    { name: 'Tamper Signals', value: 0.94 },
    { name: 'Blockchain Proof', value: 0.93 },
  ];

  const handleDownload = () => {
    const payload = {
      file: fileName,
      score,
      timestamp: new Date().toISOString(),
      summary: 'Authenticity score generated by Digital Trust Universe (demo)'
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName.replace(/\s+/g, '_')}_verification.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <section className="relative min-h-screen w-full bg-[#000814] text-white">
      <div className="mx-auto max-w-5xl px-6 pt-20">
        <div className="mb-6 flex items-center justify-between">
          <button
            onClick={onBack}
            className="inline-flex items-center gap-2 rounded-md border border-white/10 px-3 py-2 text-sm text-white/80 hover:bg-white/5"
          >
            <ArrowLeft className="h-4 w-4" /> Back
          </button>
          <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-white/70">
            <Shield className="h-3.5 w-3.5 text-[#00FFE0]" />
            Verified report
          </div>
        </div>

        <div className="grid gap-8 md:grid-cols-[280px,1fr]">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex flex-col items-center gap-4 rounded-2xl border border-white/10 bg-white/[0.06] p-6"
          >
            <Ring score={score} />
            <div className="text-center">
              <p className="text-sm uppercase tracking-wider text-white/60">Authenticity</p>
              <p className="text-lg font-semibold">High Confidence</p>
            </div>
            <button
              onClick={handleDownload}
              className="mt-2 inline-flex items-center gap-2 rounded-md bg-[#00FFE0] px-4 py-2 font-medium text-[#001219] hover:brightness-110"
            >
              <Download className="h-4 w-4" /> Download JSON
            </button>
            <button
              onClick={onRestart}
              className="mt-2 inline-flex items-center gap-2 rounded-md border border-white/10 px-4 py-2 text-white/80 hover:bg-white/5"
            >
              Start Over
            </button>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-white/10 bg-white/[0.04] p-6"
          >
            <div className="mb-6 flex items-center gap-2">
              <FileCheck className="h-5 w-5 text-[#FFD166]" />
              <h3 className="font-medium">Verification details</h3>
            </div>

            <div className="mb-6 grid gap-4 sm:grid-cols-2">
              {factors.map((f) => (
                <div key={f.name} className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
                  <div className="mb-1 flex items-center justify-between text-sm">
                    <span className="text-white/80">{f.name}</span>
                    <span className="text-white/60">{Math.round(f.value * 100)}%</span>
                  </div>
                  <div className="h-2 w-full overflow-hidden rounded-full bg-white/10">
                    <div className="h-full rounded-full bg-gradient-to-r from-[#8A2BE2] to-[#00FFE0]" style={{ width: `${f.value * 100}%` }} />
                  </div>
                </div>
              ))}
            </div>

            <div className="rounded-xl border border-white/10 bg-white/[0.02] p-4">
              <h4 className="mb-2 text-sm font-medium text-white/90">Blockchain proof</h4>
              <p className="text-sm text-white/70">
                This demo simulates hashing and anchoring. In production, a content hash is created and published to a blockchain. Verifiers can independently check the proof without revealing the document contents.
              </p>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default VerificationReport;
